In [5]:
#PARTE 1

# Pregunta 1
#importo pandas


import pandas as pd
import numpy as np

In [13]:
#importo dataset Enaho01A-2023-300.csv

df1 = pd.read_csv("/Users/sergio/Documents/GitHub/Diplomado_PUCP/_data/Enaho01A-2023-300.csv",
                  encoding = "ISO-8859-10",
                 low_memory=False)

In [15]:
df1.head(5)

SyntaxError: invalid syntax (3509654722.py, line 2)

In [16]:
# Convert the column names into a list and print it.

col_list = df1.columns.tolist()
print(col_list)

['AŅO', 'MES', 'CONGLOME', 'VIVIENDA', 'HOGAR', 'CODPERSO', 'UBIGEO', 'DOMINIO', 'ESTRATO', 'CODINFOR', 'P300N', 'P300I', 'P300A', 'P301A', 'P301B', 'P301C', 'P301D', 'P301A0', 'P301A1', 'P301B0', 'P301B1', 'P301B3', 'P302', 'P302X', 'P302A', 'P302B', 'P303', 'P304A', 'P304B', 'P304C', 'P304D', 'P305', 'P306', 'P307', 'P307A1', 'P307A2', 'P307A3', 'P307A4', 'P307A4_5', 'P307A4_6', 'P307A4_7', 'P307B1', 'P307B2', 'P307B3', 'P307B4', 'P307B4_5', 'P307B4_6', 'P307B4_7', 'P307C', 'P308A', 'P308B', 'P308C', 'P308D', 'P308B1', 'P308B2', 'P308B3', 'P308B4', 'P308B5', 'P308C1', 'P308C2', 'P310', 'P310B1', 'P310C0', 'P310C1', 'P310D1', 'P310D2', 'P310E0', 'P310E1', 'P310E3', 'P311N$1', 'P311N$2', 'P311N$3', 'P311N$4', 'P311N$5', 'P311N$6', 'P311N$7', 'P311N$8', 'P311N$9', 'P311$1', 'P311$2', 'P311$3', 'P311$4', 'P311$5', 'P311$6', 'P311$7', 'P311$8', 'P311$9', 'P311A1$1', 'P311A1$2', 'P311A1$3', 'P311A1$4', 'P311A1$5', 'P311A1$6', 'P311A1$7', 'P311A1$8', 'P311A1$9', 'P311A2$1', 'P311A2$2', 'P311A2$3', 'P311A2$4', 'P311A2$5', 'P311A2$6', 'P311A2$7', 'P311A2$8', 'P311A2$9', 'P311A3$1', 'P311A3$2', 'P311A3$3', 'P311A3$4', 'P311A3$5', 'P311A3$6', 'P311A3$7', 'P311A3$8', 'P311A3$9', 'P311A4$1', 'P311A4$2', 'P311A4$3', 'P311A4$4', 'P311A4$5', 'P311A4$6', 'P311A4$7', 'P311A4$8', 'P311A4$9', 'P311A5$1', 'P311A5$2', 'P311A5$3', 'P311A5$4', 'P311A5$5', 'P311A5$6', 'P311A5$7', 'P311A5$8', 'P311A5$9', 'P311A6$1', 'P311A6$2', 'P311A6$3', 'P311A6$4', 'P311A6$5', 'P311A6$6', 'P311A6$7', 'P311A6$8', 'P311A6$9', 'P311A7$1', 'P311A7$2', 'P311A7$3', 'P311A7$4', 'P311A7$5', 'P311A7$6', 'P311A7$7', 'P311A7$8', 'P311A7$9', 'P311B$1', 'P311B$2', 'P311B$3', 'P311B$4', 'P311B$5', 'P311B$6', 'P311B$7', 'P311B$8', 'P311B$9', 'P311C$1', 'P311C$2', 'P311C$3', 'P311C$4', 'P311C$5', 'P311C$6', 'P311C$7', 'P311C$8', 'P311C$9', 'P311D$1', 'P311D$2', 'P311D$3', 'P311D$4', 'P311D$5', 'P311D$6', 'P311D$7', 'P311D$8', 'P311D$9', 'P311D2$1', 'P311D2$2', 'P311D2$3', 'P311D2$4', 'P311D2$5', 'P311D2$6', 'P311D2$7', 'P311D2$8', 'P311D2$9', 'P311D3$1', 'P311D3$2', 'P311D3$3', 'P311D3$4', 'P311D3$5', 'P311D3$6', 'P311D3$7', 'P311D3$8', 'P311D3$9', 'P311D4$1', 'P311D4$2', 'P311D4$3', 'P311D4$4', 'P311D4$5', 'P311D4$6', 'P311D4$7', 'P311D4$8', 'P311D4$9', 'P311D5$1', 'P311D5$2', 'P311D5$3', 'P311D5$4', 'P311D5$5', 'P311D5$6', 'P311D5$7', 'P311D5$8', 'P311D5$9', 'P311D6$1', 'P311D6$2', 'P311D6$3', 'P311D6$4', 'P311D6$5', 'P311D6$6', 'P311D6$7', 'P311D6$8', 'P311D6$9', 'P311D7$1', 'P311D7$2', 'P311D7$3', 'P311D7$4', 'P311D7$5', 'P311D7$6', 'P311D7$7', 'P311D7$8', 'P311D7$9', 'P311E$1', 'P311E$2', 'P311E$3', 'P311E$4', 'P311E$5', 'P311E$6', 'P311E$7', 'P311E$8', 'P311E$9', 'P311T1', 'P311T22', 'P311T23', 'P311T24', 'P311T25', 'P311T26', 'P311T27', 'P311T2', 'P3121', 'P3121A1', 'P3121A2', 'P3121A3', 'P3121A4', 'P3121A5', 'P3121A6', 'P3121B', 'P3121C', 'P3121C2', 'P3121C3', 'P3121C4', 'P3121C5', 'P3121C6', 'P3121D', 'P3122', 'P3122A1', 'P3122A2', 'P3122A3', 'P3122A4', 'P3122A5', 'P3122A6', 'P3122B', 'P3122C', 'P3122C2', 'P3122C3', 'P3122C4', 'P3122C5', 'P3122C6', 'P3122D', 'P312T1', 'P312T22', 'P312T23', 'P312T24', 'P312T25', 'P312T26', 'P312T2', 'P313', 'P314A', 'P314B$1', 'P314B$2', 'P314B$3', 'P314B$4', 'P314B$5', 'P314B$6', 'P314B$7', 'P314B1_1', 'P314B1_2', 'P314B1_6', 'P314B1_7', 'P314B1_8', 'P314B1_9', 'P314D', 'P3151', 'P3152', 'P3153', 'P3154', 'P3155', 'P3156', 'P315A', 'P315B', 'P315B2', 'P315B3', 'P315B4', 'P315B5', 'P315B6', 'P316$1', 'P316$2', 'P316$3', 'P316$4', 'P316$5', 'P316$6', 'P316$7', 'P316$8', 'P316$9', 'P316$10', 'P316$11', 'P316$12', 'P316A1', 'P316A2', 'P316A3', 'P316A4', 'P316A5', 'P316A6', 'P316B', 'P316C1', 'P316C2', 'P316C3', 'P316C4', 'P316C5', 'P316C6', 'P316C7', 'P316C8', 'P316C9', 'P316C10', 'T313A', 'P203', 'P204', 'P205', 'P206', 'P207', 'P208A', 'P209', 'IMPUTADO', 'TICUEST01A', 'D311B$1', 'D311D2$1', 'D311D3$1', 'D311D4$1', 'D311D5$1', 'D311D6$1', 'D311D7$1', 'D311D$1', 'D311B$2', 'D311D2$2', 'D311D3$2', 'D311D4$2', 'D311D5$2', 'D311D6$2', 'D311D7$2', 'D311D$2', 'D311B$3', 'D311D2$3', 'D311D3$3', 'D311D4$3', 'D311D5$3', 'D311D6$3', 'D311D7$3', 'D311D$3', 'D311B$4', 'D311D2$4', 'D311D3$4', 'D311D4$4', 'D311D5$4', 'D311D6$4', 'D311D7$4', 'D311D$4', 'D311B$5', 'D311D2$5', 'D311D3$5', 'D311D4$5', 'D311D5$5', 'D311D6$5', 'D311D7$5', 'D311D$5', 'D311B$6', 'D311D2$6', 'D311D3$6', 'D311D4$6', 'D311D5$6', 'D311D6$6', 'D311D7$6', 'D311D$6', 'D311B$7', 'D311D2$7', 'D311D3$7', 'D311D4$7', 'D311D5$7', 'D311D6$7', 'D311D7$7', 'D311D$7', 'D3121B', 'D3121C2', 'D3121C3', 'D3121C4', 'D3121C5', 'D3121C6', 'D3121C', 'D3122B', 'D3122C2', 'D3122C3', 'D3122C4', 'D3122C5', 'D3122C6', 'D3122C', 'D315A', 'D315B2', 'D315B3', 'D315B4', 'D315B5', 'D315B6', 'D315B', 'I311B$1', 'I311B$2', 'I311B$4', 'I311B$6', 'I311B$3', 'I311B$5', 'I311B$7', 'I311D2$1', 'I311D3$1', 'I311D4$1', 'I311D5$1', 'I311D6$1', 'I311D7$1', 'I311D2$2', 'I311D3$2', 'I311D4$2', 'I311D5$2', 'I311D6$2', 'I311D7$2', 'I311D2$4', 'I311D3$4', 'I311D4$4', 'I311D5$4', 'I311D6$4', 'I311D7$4', 'I311D2$6', 'I311D3$6', 'I311D4$6', 'I311D5$6', 'I311D6$6', 'I311D7$6', 'I311D2$3', 'I311D3$3', 'I311D4$3', 'I311D5$3', 'I311D6$3', 'I311D7$3', 'I311D2$5', 'I311D3$5', 'I311D4$5', 'I311D5$5', 'I311D6$5', 'I311D7$5', 'I311D2$7', 'I311D3$7', 'I311D4$7', 'I311D5$7', 'I311D6$7', 'I311D7$7', 'I3121B', 'I3122B', 'I3121C2', 'I3121C3', 'I3121C4', 'I3121C5', 'I3121C6', 'I3122C2', 'I3122C3', 'I3122C4', 'I3122C5', 'I3122C6', 'I315A', 'I315B2', 'I315B3', 'I315B4', 'I315B5', 'I315B6', 'I311D$1', 'I311D$2', 'I311D$3', 'I311D$4', 'I311D$5', 'I311D$6', 'I311D$7', 'I3121C', 'I3122C', 'I315B', 'FACTOR07', 'FACTORA07', 'NCONGLOME', 'SUB_CONGLOME']

In [17]:
# Check the data types of the DataFrame.

df1.dtypes

AŅO               int64
MES               int64
CONGLOME          int64
VIVIENDA          int64
HOGAR             int64
                 ...
I315B            object
FACTOR07        float64
FACTORA07       float64
NCONGLOME         int64
SUB_CONGLOME      int64
Length: 511, dtype: object

In [18]:
# Select a subsample containing the variables ['CONGLOME', 'VIVIENDA', 'HOGAR', 'CODPERSO'] and between 3–5 additional variables of your interest.

df1_sub = df1[["CONGLOME", "VIVIENDA", "HOGAR", "CODPERSO", "DOMINIO", "ESTRATO", "MES"]]
df1_sub

        CONGLOME  VIVIENDA  HOGAR  CODPERSO  DOMINIO  ESTRATO  MES
0           5030         2     11         1        7        4    1
1           5030         2     11         2        7        4    1
2           5030         2     11         3        7        4    1
3           5030         2     11         4        7        4    1
4           5030        11     11         1        7        4    1
...          ...       ...    ...       ...      ...      ...  ...
108349     20670        67     11         5        4        8   12
108350     20670        68     11         1        4        8   12
108351     20670        69     11         1        4        8   12
108352     20670        69     11         2        4        8   12
108353     20670        69     11         3        4        8   12

[108354 rows x 7 columns]

In [19]:
# pregunta 2, Manipulación de data

#Explore the DataFrame using summary functions.


df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 108354 entries, 0 to 108353
Columns: 511 entries, AŅO to SUB_CONGLOME
dtypes: float64(2), int64(21), object(488)
memory usage: 422.4+ MB

In [21]:
 df1.shape

(108354, 511)

In [24]:
 df1.describe()

,AŅO,MES,CONGLOME,VIVIENDA,HOGAR,CODPERSO,UBIGEO,DOMINIO,ESTRATO,CODINFOR,...,P301A,P203,P204,P207,P208A,TICUEST01A,FACTOR07,FACTORA07,NCONGLOME,SUB_CONGLOME
count,108354.0,108354.000000,108354.000000,108354.000000,108354.000000,108354.000000,108354.000000,108354.000000,108354.000000,108354.000000,...,108354.000000,108354.000000,108354.000000,108354.000000,108354.000000,108354.000000,108354.000000,108354.000000,108354.000000,108354.000000
mean,2023.0,6.495127,16944.756797,77.820330,11.146271,2.546293,131185.171087,4.864961,4.138961,2.033058,...,5.258652,2.548729,1.005787,1.513428,35.619839,1.999539,305.556281,302.602025,23603.093914,0.282325
std,0.0,3.445244,3144.386733,68.547022,1.370084,1.577737,67736.903764,2.404443,2.432348,1.282622,...,3.807669,1.716218,0.075850,0.499822,22.152408,0.021477,310.795722,322.927385,15607.753763,0.662107
min,2023.0,1.000000,5007.000000,1.000000,11.000000,1.000000,10101.000000,1.000000,1.000000,0.000000,...,1.000000,1.000000,1.000000,1.000000,3.000000,1.000000,1.087094,0.422172,2.000000,0.000000
25%,2023.0,3.000000,16028.000000,31.000000,11.000000,1.000000,80101.000000,2.000000,2.000000,1.000000,...,3.000000,1.000000,1.000000,1.000000,16.000000,2.000000,123.659256,101.125488,8855.000000,0.000000
50%,2023.0,7.000000,17500.000000,66.000000,11.000000,2.000000,140108.000000,5.000000,4.000000,2.000000,...,5.000000,3.000000,1.000000,2.000000,33.000000,2.000000,233.634140,218.866760,20186.000000,0.000000
75%,2023.0,9.000000,19014.000000,106.000000,11.000000,3.000000,180301.000000,7.000000,7.000000,2.000000,...,6.000000,3.000000,1.000000,2.000000,53.000000,2.000000,354.661774,365.609833,37361.000000,0.000000
max,2023.0,12.000000,21001.000000,991.000000,44.000000,22.000000,250401.000000,8.000000,8.000000,21.000000,...,99.000000,11.000000,2.000000,2.000000,98.000000,2.000000,1961.005981,2917.495850,51561.000000,6.000000

In [30]:
# Identify if there are missing values. If they exist, remove them.

df1_nulls = df1.isnull().sum()
df1_nulls

AŅO             0
MES             0
CONGLOME        0
VIVIENDA        0
HOGAR           0
               ..
I315B           0
FACTOR07        0
FACTORA07       0
NCONGLOME       0
SUB_CONGLOME    0
Length: 511, dtype: int64

In [31]:
df1 = df1.dropna()
df1

,AŅO,MES,CONGLOME,VIVIENDA,HOGAR,CODPERSO,UBIGEO,DOMINIO,ESTRATO,CODINFOR,...,I311D$5,I311D$6,I311D$7,I3121C,I3122C,I315B,FACTOR07,FACTORA07,NCONGLOME,SUB_CONGLOME
0,2023,1,5030,2,11,1,10201,7,4,1,...,,,,,,,118.374542,165.623856,6618,0
1,2023,1,5030,2,11,2,10201,7,4,2,...,,,,,,,118.374542,112.328087,6618,0
2,2023,1,5030,2,11,3,10201,7,4,2,...,,,,,,,118.374542,120.091476,6618,0
3,2023,1,5030,2,11,4,10201,7,4,2,...,,,8,,,,118.374542,110.974678,6618,0
4,2023,1,5030,11,11,1,10201,7,4,1,...,,,,,,,118.374542,96.035370,6618,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108349,2023,12,20670,67,11,5,10503,4,8,2,...,,,,,,,65.991585,76.758545,7051,0
108350,2023,12,20670,68,11,1,10503,4,8,1,...,,,,,,,65.991585,94.397972,7051,0
108351,2023,12,20670,69,11,1,10503,4,8,1,...,,,,,,,65.991585,54.246708,7051,0
108352,2023,12,20670,69,11,2,10503,4,8,2,...,,,,,,,65.991585,69.487373,7051,0
108353,2023,12,20670,69,11,3,10503,4,8,3,...,,,,,,,65.991585,94.397972,7051,0

In [33]:
# pregunta 3
#Import a second dataset (choose between Enaho01A-2023-200.csv or Enaho01A-2023-500.csv).

df2 = pd.read_csv("/Users/sergio/Documents/GitHub/Diplomado_PUCP/_data/Enaho01a-2023-500.csv", 
                  encoding = "ISO-8859-10" ,
                   low_memory=False)

In [34]:
# display 5 rows
df2.head(5)

,AŅO,MES,CONGLOME,VIVIENDA,HOGAR,CODPERSO,UBIGEO,DOMINIO,ESTRATO,CODINFOR,...,I538E1,I5294B,I5404B,I541A,OCU500,OCUPINF,EMPLPSEC,FAC500A,NCONGLOME,SUB_CONGLOME
0,2023,1,5030,2,11,1,10201,7,4,1,...,,,,,1,2,,165.623856,6618,0
1,2023,1,5030,2,11,2,10201,7,4,2,...,,,,,1,2,,112.328087,6618,0
2,2023,1,5030,11,11,1,10201,7,4,1,...,,,,,1,1,1,96.035370,6618,0
3,2023,1,5030,11,11,2,10201,7,4,2,...,,,,,1,1,1,86.868881,6618,0
4,2023,1,5030,11,11,3,10201,7,4,3,...,,,,,1,1,1,185.492355,6618,0

In [35]:
# Convert the column names into a list and print it.

df2_cols = df2.columns.tolist()
print(df2_cols)

['AŅO', 'MES', 'CONGLOME', 'VIVIENDA', 'HOGAR', 'CODPERSO', 'UBIGEO', 'DOMINIO', 'ESTRATO', 'CODINFOR', 'P500A', 'P500B', 'P500B1', 'P500C', 'P500D', 'P500D1', 'P500N', 'P500I', 'P501', 'P502', 'P503', 'P504', 'P5041', 'P5042', 'P5043', 'P5044', 'P5045', 'P5046', 'P5047', 'P5048', 'P5049', 'P50410', 'P50411', 'P505', 'P505R4', 'P505B', 'P506', 'P506R4', 'P507', 'P508', 'P509', 'P510', 'P510A1', 'P510B', 'P5111', 'P5112', 'P5113', 'P5114', 'P5115', 'P5116', 'P5117', 'P5118', 'P5119', 'P51110', 'P51111', 'P51112', 'P511A', 'P512A', 'P512B', 'P513', 'P513A', 'P513B', 'P513C', 'P513D', 'P513E', 'P513F', 'P513G', 'P513T', 'P513A1', 'P513A2', 'P514', 'P5151', 'P5152', 'P5153', 'P5154', 'P5155', 'P5156', 'P5157', 'P5158', 'P5159', 'P51510', 'P51511', 'P516', 'P516R4', 'P517', 'P517A', 'P517B1', 'P517C', 'P517D1', 'P517D2', 'P518', 'P519', 'P520', 'P520A', 'P521', 'P521A', 'P521B', 'P521B1', 'P521C', 'P521D', 'P523', 'P524A1', 'P524A2', 'P524B1', 'P524B2', 'P524C1', 'P524C2', 'P524D1', 'P524D2', 'P524E1', 'P524E2', 'P528', 'P5291A', 'P5291B', 'P5291C', 'P5292A', 'P5292B', 'P5292C', 'P5293A', 'P5293B', 'P5293C', 'P5294A', 'P5294B', 'P5294C', 'P5295A', 'P5295B', 'P5295C', 'P5296A', 'P5296B', 'P5296C', 'P529T', 'P5297A', 'P530A', 'P530B', 'P535', 'P536', 'P5371', 'P5372', 'P5373', 'P5374', 'P5375', 'P5376', 'P5377', 'P5378', 'P5379', 'P53710', 'P53711', 'P53712', 'P538A1', 'P538A2', 'P538B1', 'P538B2', 'P538C1', 'P538C2', 'P538D1', 'P538D2', 'P538E1', 'P538E2', 'P539', 'P5401A', 'P5401B', 'P5401C', 'P5402A', 'P5402B', 'P5402C', 'P5403A', 'P5403B', 'P5403C', 'P5404A', 'P5404B', 'P5404C', 'P5405A', 'P5405B', 'P5405C', 'P5406A', 'P5406B', 'P5406C', 'P540T', 'P5407A', 'P541A', 'P541B', 'P542', 'P543', 'P5441A', 'P5441B', 'P5442A', 'P5442B', 'P5443A', 'P5443B', 'P5444A', 'P5444B', 'P5445A', 'P5445B', 'P5446A', 'P5446B', 'P5447A', 'P5447B', 'P5448A', 'P5448B', 'P544T', 'P545', 'P546', 'P547', 'P548', 'P549', 'P550_1', 'P550_2', 'P550_3', 'P550_4', 'P550_5', 'P550_6', 'P550_7', 'P550_GI', 'P551', 'P552', 'P554', 'P554R4', 'P555', 'P5561A', 'P5561B', 'P5561C', 'P5561D', 'P5561E', 'P5562A', 'P5562B', 'P5562C', 'P5562D', 'P5562E', 'P5563A', 'P5563B', 'P5563C', 'P5563C1', 'P5563D', 'P5563E', 'P5563F', 'P5563G', 'P5564A', 'P5564B', 'P5564C', 'P5564D', 'P5564E', 'P5565A', 'P5565B', 'P5565C', 'P5565D', 'P5565E', 'P5566A', 'P5566B', 'P5566C', 'P5566D', 'P5566E', 'P5567A', 'P5567B', 'P5567C', 'P5567D', 'P5567E', 'P5568A', 'P5568B', 'P5568C', 'P5568D', 'P5568E', 'P5569A', 'P5569B', 'P5569C', 'P5569D', 'P5569E', 'P55610A', 'P55610B', 'P55610C', 'P55610D', 'P55610E', 'P55611A', 'P55611B', 'P55611C', 'P55611D', 'P55611E', 'P55612A', 'P55612B', 'P55612C', 'P55612D', 'P55612E', 'P55613A', 'P55613B', 'P55613C', 'P55613D', 'P55613E', 'P55614A', 'P55614B', 'P55614C', 'P55614D', 'P55614E', 'P55620A', 'P55620B', 'P55620C', 'P55620D', 'P55620E', 'P55621A', 'P55621B', 'P55621C', 'P55621D', 'P55621E', 'P55622A', 'P55622B', 'P55622C', 'P55622D', 'P55622E', 'P55623A', 'P55623B', 'P55623C', 'P55623D', 'P55623E', 'P55624A', 'P55624B', 'P55624C', 'P55624D', 'P55624E', 'P55625A', 'P55625B', 'P55625C', 'P55625D', 'P55625E', 'P55626A', 'P55626B', 'P55626C', 'P55626D', 'P55626E', 'P55627A', 'P55627B', 'P55627C', 'P55627D', 'P55627E', 'P55628A', 'P55628B', 'P55628C', 'P55628D', 'P55628E', 'P556T1', 'P556T2', 'P5571A', 'P5571B', 'P5571C', 'P5572A', 'P5572B', 'P5572C', 'P5573A', 'P5573B', 'P5573C', 'P5574A', 'P5574B', 'P5574C', 'P5575A', 'P5575B', 'P5575C', 'P5576A', 'P5576B', 'P5576C', 'P5577A', 'P5577B', 'P5577C', 'P5578A', 'P5578B', 'P5578C', 'P557T', 'P5581A', 'P5581B', 'P5582A', 'P5582B', 'P5583A', 'P5583B', 'P5584A', 'P5584B', 'P5585A', 'P5585B', 'P5586A', 'P5586B', 'P5587A', 'P5587B', 'P5588A', 'P5588B', 'P5589A', 'P5589B', 'P55810A', 'P55810B', 'P558T', 'P558T1', 'P558A1', 'P558A2', 'P558A3', 'P558A4', 'P558A5', 'P558B1', 'P558B2', 'P558B3', 'P558C', 'P558D2_1', 'P558D2_2', 'P558E1_1', 'P558E1_2', 'P558E1_3', 'P558E1_6', 'P558E1_7', 'P558E2_1', 'P558E3_1', 'P558E2_2', 'P558E3_2', 'P558F1A', 'P558F1B', 'P558G1', 'P558G2', 'P558G3', 'P558G5', 'P558G6', 'P558G7', 'P558H1_1', 'P558H1_2', 'P558H1_3', 'P558H1_4', 'P558H1_5', 'P558H1_6', 'P558H2_1', 'P558H2_2', 'P558H2_3', 'P558H2_4', 'P558H2_5', 'P558H2_6', 'P558H3_1', 'P558H3_2', 'P558H3_3', 'P558H3_4', 'P558H3_5', 'P558H3_6', 'P558H4_1', 'P558H4_2', 'P558H4_3', 'P558H4_4', 'P558H4_5', 'P558H4_6', 'P558H5_1', 'P558H5_2', 'P558H5_3', 'P558H5_4', 'P558H5_5', 'P558H5_6', 'P558H6_1', 'P558H6_2', 'P558H6_3', 'P558H6_4', 'P558H6_5', 'P558H6_6', 'P558H7_1', 'P558H7_2', 'P558H7_3', 'P558H7_4', 'P558H7_5', 'P558H7_6', 'P558H8_1', 'P558H8_2', 'P558H8_3', 'P558H8_4', 'P558H8_5', 'P558H8_6', 'P558H9_1', 'P558H9_2', 'P558H9_3', 'P558H9_4', 'P558H9_5', 'P558H9_6', 'P558H10_1', 'P558H10_2', 'P558H10_3', 'P558H10_4', 'P558H10_5', 'P558H10_6', 'P558H11_1', 'P558H11_2', 'P558H11_3', 'P558H11_4', 'P558H11_5', 'P558H11_6', 'P558H12_1', 'P558H12_2', 'P558H12_3', 'P558H12_4', 'P558H12_5', 'P558H12_6', 'P559$01', 'P559$02', 'P559$03', 'P559$04', 'P559$05', 'P559$06', 'P559$07', 'P559$08', 'P559$09', 'P559$10', 'P559$11', 'P559$12', 'P559$13', 'P559$14', 'P559$15', 'P559$16', 'P559$17', 'P559$18', 'P559$19', 'P559$20', 'P559$21', 'P559$22', 'P559$23', 'P559$24', 'P559$25', 'P559$26', 'P559$27', 'P559$28', 'P559$29', 'P559$30', 'P559$31', 'P559$32', 'P559$33', 'P559$34', 'P559$35', 'P559$36', 'P559$37', 'P559$38', 'P559$39', 'P559$40', 'P559$41', 'P559$42', 'P559$43', 'P559$44', 'P559$45', 'P559$46', 'P559$47', 'P559$48', 'P559$49', 'P559$50', 'P559T$01', 'P559T$02', 'P559T$03', 'P559T$04', 'P559T$05', 'P559T$06', 'P559T$07', 'P559T$08', 'P559T$09', 'P559T$10', 'P559T$11', 'P559T$12', 'P559T$13', 'P559T$14', 'P559T$15', 'P559T$16', 'P559T$17', 'P559T$18', 'P559T$19', 'P559T$20', 'P559T$21', 'P559T$22', 'P559T$23', 'P559T$24', 'P559T$25', 'P559T$26', 'P559T$27', 'P559T$28', 'P559T$29', 'P559T$30', 'P559T$31', 'P559T$32', 'P559T$33', 'P559T$34', 'P559T$35', 'P559T$36', 'P559T$37', 'P559T$38', 'P559T$39', 'P559T$40', 'P559T$41', 'P559T$42', 'P559T$43', 'P559T$44', 'P559T$45', 'P559T$46', 'P559T$47', 'P559T$48', 'P559T$49', 'P559T$50', 'P559A$01', 'P559A$02', 'P559A$03', 'P559A$04', 'P559A$05', 'P559A$06', 'P559A$07', 'P559A$08', 'P559A$09', 'P559A$10', 'P559A$11', 'P559A$12', 'P559A$13', 'P559A$14', 'P559A$15', 'P559A$16', 'P559A$17', 'P559A$18', 'P559A$19', 'P559A$20', 'P559A$21', 'P559A$22', 'P559A$23', 'P559A$24', 'P559A$25', 'P559A$26', 'P559A$27', 'P559A$28', 'P559A$29', 'P559A$30', 'P559A$31', 'P559A$32', 'P559A$33', 'P559A$34', 'P559A$35', 'P559A$36', 'P559A$37', 'P559A$38', 'P559A$39', 'P559A$40', 'P559A$41', 'P559A$42', 'P559A$43', 'P559A$44', 'P559A$45', 'P559A$46', 'P559A$47', 'P559A$48', 'P559A$49', 'P559A$50', 'P559B$01', 'P559B$02', 'P559B$03', 'P559B$04', 'P559B$05', 'P559B$06', 'P559B$07', 'P559B$08', 'P559B$09', 'P559B$10', 'P559B$11', 'P559B$12', 'P559B$13', 'P559B$14', 'P559B$15', 'P559B$16', 'P559B$17', 'P559B$18', 'P559B$19', 'P559B$20', 'P559B$21', 'P559B$22', 'P559B$23', 'P559B$24', 'P559B$25', 'P559B$26', 'P559B$27', 'P559B$28', 'P559B$29', 'P559B$30', 'P559B$31', 'P559B$32', 'P559B$33', 'P559B$34', 'P559B$35', 'P559B$36', 'P559B$37', 'P559B$38', 'P559B$39', 'P559B$40', 'P559B$41', 'P559B$42', 'P559B$43', 'P559B$44', 'P559B$45', 'P559B$46', 'P559B$47', 'P559B$48', 'P559B$49', 'P559B$50', 'P559C$01', 'P559C$02', 'P559C$03', 'P559C$04', 'P559C$05', 'P559C$06', 'P559C$07', 'P559C$08', 'P559C$09', 'P559C$10', 'P559C$11', 'P559C$12', 'P559C$13', 'P559C$14', 'P559C$15', 'P559C$16', 'P559C$17', 'P559C$18', 'P559C$19', 'P559C$20', 'P559C$21', 'P559C$22', 'P559C$23', 'P559C$24', 'P559C$25', 'P559C$26', 'P559C$27', 'P559C$28', 'P559C$29', 'P559C$30', 'P559C$31', 'P559C$32', 'P559C$33', 'P559C$34', 'P559C$35', 'P559C$36', 'P559C$37', 'P559C$38', 'P559C$39', 'P559C$40', 'P559C$41', 'P559C$42', 'P559C$43', 'P559C$44', 'P559C$45', 'P559C$46', 'P559C$47', 'P559C$48', 'P559C$49', 'P559C$50', 'P559D$01', 'P559D$02', 'P559D$03', 'P559D$04', 'P559D$05', 'P559D$06', 'P559D$07', 'P559D$08', 'P559D$09', 'P559D$10', 'P559D$11', 'P559D$12', 'P559D$13', 'P559D$14', 'P559D$15', 'P559D$16', 'P559D$17', 'P559D$18', 'P559D$19', 'P559D$20', 'P559D$21', 'P559D$22', 'P559D$23', 'P559D$24', 'P559D$25', 'P559D$26', 'P559D$27', 'P559D$28', 'P559D$29', 'P559D$30', 'P559D$31', 'P559D$32', 'P559D$33', 'P559D$34', 'P559D$35', 'P559D$36', 'P559D$37', 'P559D$38', 'P559D$39', 'P559D$40', 'P559D$41', 'P559D$42', 'P559D$43', 'P559D$44', 'P559D$45', 'P559D$46', 'P559D$47', 'P559D$48', 'P559D$49', 'P559D$50', 'P559E$01', 'P559E$02', 'P559E$03', 'P559E$04', 'P559E$05', 'P559E$06', 'P559E$07', 'P559E$08', 'P559E$09', 'P559E$10', 'P559E$11', 'P559E$12', 'P559E$13', 'P559E$14', 'P559E$15', 'P559E$16', 'P559E$17', 'P559E$18', 'P559E$19', 'P559E$20', 'P559E$21', 'P559E$22', 'P559E$23', 'P559E$24', 'P559E$25', 'P559E$26', 'P559E$27', 'P559E$28', 'P559E$29', 'P559E$30', 'P559E$31', 'P559E$32', 'P559E$33', 'P559E$34', 'P559E$35', 'P559E$36', 'P559E$37', 'P559E$38', 'P559E$39', 'P559E$40', 'P559E$41', 'P559E$42', 'P559E$43', 'P559E$44', 'P559E$45', 'P559E$46', 'P559E$47', 'P559E$48', 'P559E$49', 'P559E$50', 'P59F1$01', 'P59F1$02', 'P59F1$03', 'P59F1$04', 'P59F1$05', 'P59F1$06', 'P59F1$07', 'P59F1$08', 'P59F1$09', 'P59F1$10', 'P59F1$11', 'P59F1$12', 'P59F1$13', 'P59F1$14', 'P59F1$15', 'P59F1$16', 'P59F1$17', 'P59F1$18', 'P59F1$19', 'P59F1$20', 'P59F1$21', 'P59F1$22', 'P59F1$23', 'P59F1$24', 'P59F1$25', 'P59F1$26', 'P59F1$27', 'P59F1$28', 'P59F1$29', 'P59F1$30', 'P59F1$31', 'P59F1$32', 'P59F1$33', 'P59F1$34', 'P59F1$35', 'P59F1$36', 'P59F1$37', 'P59F1$38', 'P59F1$39', 'P59F1$40', 'P59F1$41', 'P59F1$42', 'P59F1$43', 'P59F1$44', 'P59F1$45', 'P59F1$46', 'P59F1$47', 'P59F1$48', 'P59F1$49', 'P59F1$50', 'P59F2$01', 'P59F2$02', 'P59F2$03', 'P59F2$04', 'P59F2$05', 'P59F2$06', 'P59F2$07', 'P59F2$08', 'P59F2$09', 'P59F2$10', 'P59F2$11', 'P59F2$12', 'P59F2$13', 'P59F2$14', 'P59F2$15', 'P59F2$16', 'P59F2$17', 'P59F2$18', 'P59F2$19', 'P59F2$20', 'P59F2$21', 'P59F2$22', 'P59F2$23', 'P59F2$24', 'P59F2$25', 'P59F2$26', 'P59F2$27', 'P59F2$28', 'P59F2$29', 'P59F2$30', 'P59F2$31', 'P59F2$32', 'P59F2$33', 'P59F2$34', 'P59F2$35', 'P59F2$36', 'P59F2$37', 'P59F2$38', 'P59F2$39', 'P59F2$40', 'P59F2$41', 'P59F2$42', 'P59F2$43', 'P59F2$44', 'P59F2$45', 'P59F2$46', 'P59F2$47', 'P59F2$48', 'P59F2$49', 'P59F2$50', 'P560T$01', 'P560T$02', 'P560T$03', 'P560T$04', 'P560T$05', 'P560T$06', 'P560T$07', 'P560T$08', 'P560T$09', 'P560T$10', 'P560A1$01', 'P560A1$02', 'P560A1$03', 'P560A1$04', 'P560A1$05', 'P560A1$06', 'P560A1$07', 'P560A1$08', 'P560A1$09', 'P560A1$10', 'P560A$01', 'P560A$02', 'P560A$03', 'P560A$04', 'P560A$05', 'P560A$06', 'P560A$07', 'P560A$08', 'P560A$09', 'P560A$10', 'P560C$01', 'P560C$02', 'P560C$03', 'P560C$04', 'P560C$05', 'P560C$06', 'P560C$07', 'P560C$08', 'P560C$09', 'P560C$10', 'P560D$01', 'P560D$02', 'P560D$03', 'P560D$04', 'P560D$05', 'P560D$06', 'P560D$07', 'P560D$08', 'P560D$09', 'P560D$10', 'P560E$01', 'P560E$02', 'P560E$03', 'P560E$04', 'P560E$05', 'P560E$06', 'P560E$07', 'P560E$08', 'P560E$09', 'P560E$10', 'P560F1$01', 'P560F1$02', 'P560F1$03', 'P560F1$04', 'P560F1$05', 'P560F1$06', 'P560F1$07', 'P560F1$08', 'P560F1$09', 'P560F1$10', 'P560F2$01', 'P560F2$02', 'P560F2$03', 'P560F2$04', 'P560F2$05', 'P560F2$06', 'P560F2$07', 'P560F2$08', 'P560F2$09', 'P560F2$10', 'P599', 'P203', 'P204', 'P205', 'P206', 'P207', 'P208A', 'P209', 'P301A', 'IMPUTADO', 'TICUEST01A', 'D524A1', 'D524B1', 'D524C1', 'D524D1', 'D524E1', 'D5291B', 'D5292B', 'D5293B', 'D5294B', 'D5295B', 'D5296B', 'D529T', 'D530A', 'D536', 'D538A1', 'D538B1', 'D538C1', 'D538D1', 'D538E1', 'D5401B', 'D5402B', 'D5403B', 'D5404B', 'D5405B', 'D5406B', 'D540T', 'D541A', 'D543', 'D5441B', 'D5442B', 'D5443B', 'D5444B', 'D5445B', 'D5446B', 'D5447B', 'D5448B', 'D544T', 'D5561C', 'D5561E', 'D5562C', 'D5562E', 'D5563C', 'D5563E', 'D5564C', 'D5564E', 'D5565C', 'D5565E', 'D5566C', 'D5566E', 'D5567C', 'D5567E', 'D5568C', 'D5568E', 'D5569C', 'D5569E', 'D55610C', 'D55610E', 'D55611C', 'D55611E', 'D55612C', 'D55612E', 'D55613C', 'D55613E', 'D55614C', 'D55614E', 'D55620C', 'D55620E', 'D55621C', 'D55621E', 'D55622C', 'D55622E', 'D55623C', 'D55623E', 'D55624C', 'D55624E', 'D55625C', 'D55625E', 'D55626C', 'D55626E', 'D55627C', 'D55627E', 'D55628C', 'D55628E', 'D556T1', 'D556T2', 'D5571C', 'D5572C', 'D5573C', 'D5574C', 'D5575C', 'D5576C', 'D5577C', 'D5578C', 'D557T', 'D558T', 'D559D1', 'D559D2', 'D559D3', 'D559D41', 'D559D42', 'D559D43', 'D559D44', 'D559D45', 'D559D46', 'D559D47', 'D559D48', 'D559D49', 'D559D410', 'D559D411', 'D559D412', 'D559D413', 'D559D414', 'D559D415', 'D559D416', 'D559D417', 'D559D418', 'D559D419', 'D559D420', 'D559D421', 'D559D422', 'D559D423', 'D559D424', 'D559D425', 'D559D426', 'D559D427', 'D559D428', 'D559D429', 'D559D430', 'D559D431', 'D559D432', 'D559D433', 'D559D434', 'D559D435', 'D559D436', 'D559D437', 'D559D438', 'D559D439', 'D559D440', 'D559D441', 'D559D442', 'D559D443', 'D559D444', 'D559D445', 'D559D446', 'D559D447', 'D560D1', 'D560D2', 'D560D3', 'D560D4', 'D560D5', 'D560D6', 'D560D7', 'D560D8', 'D560D9', 'D560D10', 'T559B$01', 'T559B$02', 'T559B$03', 'T559B$04', 'T559B$05', 'T559B$06', 'T559B$07', 'T559B$08', 'T559B$09', 'T559B$10', 'T559B$11', 'T559B$12', 'T559B$13', 'T559B$14', 'T559B$15', 'T559B$16', 'T559B$17', 'T559B$18', 'T559B$19', 'T559B$20', 'T559B$21', 'T559B$22', 'T559B$23', 'T559B$24', 'T559B$25', 'T559B$26', 'T559B$27', 'T559B$28', 'T559B$29', 'T559B$30', 'T559B$31', 'T559B$32', 'T559B$33', 'T559B$34', 'T559B$35', 'T559B$36', 'T559B$37', 'T559B$38', 'T559B$39', 'T559B$40', 'T559B$41', 'T559B$42', 'T559B$43', 'T559B$44', 'T559B$45', 'T559B$46', 'T559B$47', 'T559B$48', 'T559B$49', 'T559B$50', 'Z559B$01', 'Z559B$02', 'Z559B$03', 'Z559B$04', 'Z559B$05', 'Z559B$06', 'Z559B$07', 'Z559B$08', 'Z559B$09', 'Z559B$10', 'Z559B$11', 'Z559B$12', 'Z559B$13', 'Z559B$14', 'Z559B$15', 'Z559B$16', 'Z559B$17', 'Z559B$18', 'Z559B$19', 'Z559B$20', 'Z559B$21', 'Z559B$22', 'Z559B$23', 'Z559B$24', 'Z559B$25', 'Z559B$26', 'Z559B$27', 'Z559B$28', 'Z559B$29', 'Z559B$30', 'Z559B$31', 'Z559B$32', 'Z559B$33', 'Z559B$34', 'Z559B$35', 'Z559B$36', 'Z559B$37', 'Z559B$38', 'Z559B$39', 'Z559B$40', 'Z559B$41', 'Z559B$42', 'Z559B$43', 'Z559B$44', 'Z559B$45', 'Z559B$46', 'Z559B$47', 'Z559B$48', 'Z559B$49', 'Z559B$50', 'I559D1', 'I559D2', 'I559D3', 'I559D41', 'I559D42', 'I559D43', 'I559D44', 'I559D45', 'I559D46', 'I559D47', 'I559D48', 'I559D49', 'I559D410', 'I559D411', 'I559D412', 'I559D413', 'I559D414', 'I559D415', 'I559D416', 'I559D417', 'I559D418', 'I559D419', 'I559D420', 'I559D421', 'I559D422', 'I559D423', 'I559D424', 'I559D425', 'I559D426', 'I559D427', 'I559D428', 'I559D429', 'I559D430', 'I559D431', 'I559D432', 'I559D433', 'I559D434', 'I559D435', 'I559D436', 'I559D437', 'I559D438', 'I559D439', 'I559D440', 'I559D441', 'I559D442', 'I559D443', 'I559D444', 'I559D445', 'I559D446', 'I559D447', 'I560D1', 'I560D2', 'I560D3', 'I560D4', 'I560D5', 'I560D6', 'I560D7', 'I560D8', 'I560D9', 'I560D10', 'R559_01', 'R559_02', 'R559_03', 'R559_04', 'R559_05', 'R559_06', 'R559_07', 'R559_08', 'R559_09', 'R559_10', 'R559_11', 'R559_12', 'R559_13', 'R559_14', 'R559_15', 'R559_16', 'R559_17', 'R559_18', 'R559_19', 'R559_20', 'R559_21', 'R559_22', 'R559_23', 'R559_24', 'R559_25', 'R559_26', 'R559_27', 'R559_28', 'R559_29', 'R559_30', 'R559_31', 'R559_32', 'R559_33', 'R559_34', 'R559_35', 'R559_36', 'R559_37', 'R559_38', 'R559_39', 'R559_40', 'R559_41', 'R559_42', 'R559_43', 'R559_44', 'R559_45', 'R559_46', 'R559_47', 'R559_48', 'R559_49', 'R559_50', 'I518', 'I513T', 'I520', 'I530A', 'I524A1', 'I524B1', 'I524C1', 'I524D1', 'I524E1', 'I538A1', 'I538B1', 'I538C1', 'I538D1', 'I538E1', 'I5294B', 'I5404B', 'I541A', 'OCU500', 'OCUPINF', 'EMPLPSEC', 'FAC500A', 'NCONGLOME', 'SUB_CONGLOME']

In [36]:
#chequea lostipos de data 

df2.dtypes

AŅO               int64
MES               int64
CONGLOME          int64
VIVIENDA          int64
HOGAR             int64
                 ...
OCUPINF          object
EMPLPSEC         object
FAC500A         float64
NCONGLOME         int64
SUB_CONGLOME      int64
Length: 1414, dtype: object

In [38]:
# selecciona los subsamples a las de las variables y 3 variables o 5 ['CONGLOME', 'VIVIENDA', 'HOGAR', 'CODPERSO']


df2_sub = df2[['CONGLOME', 'VIVIENDA', 'HOGAR', 'CODPERSO', 'EMPLPSEC', 'TICUEST01A', 'OCUPINF', 'SUB_CONGLOME']]
df2_sub

,CONGLOME,VIVIENDA,HOGAR,CODPERSO,EMPLPSEC,TICUEST01A,OCUPINF,SUB_CONGLOME
0,5030,2,11,1,,2,2,0
1,5030,2,11,2,,2,2,0
2,5030,11,11,1,1,2,1,0
3,5030,11,11,2,1,2,1,0
4,5030,11,11,3,1,2,1,0
...,...,...,...,...,...,...,...,...
86649,20670,67,11,2,1,2,1,0
86650,20670,68,11,1,1,2,1,0
86651,20670,69,11,1,1,2,1,0
86652,20670,69,11,2,1,2,1,0
86653,20670,69,11,3,1,2,1,0

In [40]:
# Perform the following modifications:
#A. Change the data type of a variable (e.g., from text to numeric).

df2["P301A"] = df2['P301A'].astype(str)
print(df2['P301A'].dtype)

object

In [42]:
#B. modifing some values

df2["VIVIENDA"] = df2["VIVIENDA"] * 3 +2

df2[["VIVIENDA"]].head()

   VIVIENDA
0         8
1         8
2        35
3        35
4        35

In [43]:
# pregunta 4 - Merge


common_columns = df1.columns.intersection(df2.columns).tolist()
print(common_columns)

['AŅO', 'MES', 'CONGLOME', 'VIVIENDA', 'HOGAR', 'CODPERSO', 'UBIGEO', 'DOMINIO', 'ESTRATO', 'CODINFOR', 'P301A', 'P203', 'P204', 'P205', 'P206', 'P207', 'P208A', 'P209', 'IMPUTADO', 'TICUEST01A', 'NCONGLOME', 'SUB_CONGLOME']

In [59]:
# Inicio de merge

common_columns = ['CONGLOME', 'VIVIENDA', 'HOGAR', 'CODPERSO']

merged_df = pd.merge(df1, df2, on=common_columns, how="inner")
merged_df.head(5)

,AŅO_x,MES_x,CONGLOME,VIVIENDA,HOGAR,CODPERSO,UBIGEO_x,DOMINIO_x,ESTRATO_x,CODINFOR_x,...,I538E1,I5294B,I5404B,I541A,OCU500,OCUPINF,EMPLPSEC,FAC500A,NCONGLOME_y,SUB_CONGLOME_y
0,2023,1,6921,47,11,1,120107,5,2,1,...,,,,,1,1,1,168.550827,32160,0
1,2023,1,6921,47,11,2,120107,5,2,2,...,,,,,1,1,1,166.963043,32160,0
2,2023,1,6921,47,11,3,120107,5,2,3,...,,,,,4,,,87.799217,32160,0
3,2023,1,8825,149,11,1,200501,1,3,1,...,,,,2235,1,2,,315.374298,637,0
4,2023,1,8825,149,11,2,200501,1,3,2,...,,,,,1,2,,235.571411,637,0

In [61]:
# pregunta 5 elegir un indicador estadístico

merged_df = merged_df.groupby("CODPERSO").mean(numeric_only = True)
merged_df

,AŅO_x,MES_x,CONGLOME,HOGAR,UBIGEO_x,DOMINIO_x,ESTRATO_x,CODINFOR_x,P300N,P300I,...,P203_y,P204_y,P207_y,P208A_y,P209_y,TICUEST01A_y,OCU500,FAC500A,NCONGLOME_y,SUB_CONGLOME_y
CODPERSO,,,,,,,,,,,,,,,,,,,,,
1.000000,2023.0,8.000000,17419.000000,11.0,125203.500000,1.500000,7.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,64.000000,3.500000,2.0,2.500000,102.610832,18775.000000,0.000000
1.250000,2023.0,8.000000,14000.000000,11.0,202602.250000,4.000000,3.500000,1.250000,1.250000,1.250000,...,1.250000,1.000000,1.250000,62.750000,2.750000,2.0,1.000000,153.189617,17283.500000,0.000000
1.333333,2023.0,9.000000,15018.666667,11.0,156910.000000,7.333333,5.666667,1.333333,1.333333,1.333333,...,1.333333,1.000000,1.666667,52.333333,2.333333,2.0,2.000000,467.909360,12197.333333,0.000000
1.357143,2023.0,8.714286,16769.107143,11.0,124299.678571,4.607143,3.857143,1.214286,1.357143,1.214286,...,1.642857,1.000000,1.464286,57.892857,3.178571,2.0,2.071429,410.734473,19519.642857,0.500000
1.375000,2023.0,6.375000,14247.750000,11.0,89279.000000,4.875000,5.125000,1.500000,1.375000,1.500000,...,1.625000,1.000000,1.500000,46.000000,3.500000,2.0,1.750000,130.901145,33647.375000,0.500000
1.400000,2023.0,6.500000,17210.250000,11.0,109252.700000,4.550000,5.150000,1.350000,1.400000,1.350000,...,1.500000,1.000000,1.450000,52.500000,2.250000,2.0,1.800000,263.673173,24092.450000,0.000000
1.500000,2023.0,7.080247,16528.629630,11.0,79833.882716,4.080247,6.858025,1.425926,1.500000,1.425926,...,1.833333,1.000000,1.376543,45.429012,3.141975,2.0,2.027778,147.206103,20241.172840,0.055556
1.538462,2023.0,6.884615,16532.500000,11.0,114995.730769,5.269231,4.423077,1.615385,1.538462,1.615385,...,2.000000,1.000000,1.500000,52.500000,3.230769,2.0,1.807692,339.657176,19822.115385,0.153846
1.545455,2023.0,7.000000,15501.363636,11.0,160174.727273,5.636364,3.636364,1.545455,1.545455,1.545455,...,1.454545,1.000000,1.545455,58.636364,2.454545,2.0,1.818182,278.267346,21267.181818,0.000000
1.571429,2023.0,6.342857,15608.542857,11.0,138587.742857,5.142857,4.285714,1.514286,1.571429,1.514286,...,1.800000,1.028571,1.514286,51.542857,2.828571,2.0,1.828571,271.665285,32130.914286,0.285714
1.588235,2023.0,6.294118,17117.411765,11.0,103380.588235,5.470588,3.058824,1.588235,1.588235,1.588235,...,1.588235,1.000000,1.470588,57.705882,2.470588,2.0,1.705882,301.943112,16393.588235,0.235294
1.600000,2023.0,4.400000,13203.100000,11.0,159392.700000,3.300000,6.100000,1.700000,1.600000,1.700000,...,1.700000,1.000000,1.500000,41.100000,2.800000,2.0,1.700000,121.812041,20299.800000,0.000000
1.625000,2023.0,6.256944,16114.083333,11.0,88091.326389,4.916667,4.513889,1.562500,1.625000,1.562500,...,2.020833,1.000000,1.513889,46.305556,3.104167,2.0,1.583333,243.087283,25986.951389,0.402778
1.666667,2023.0,5.800000,17560.800000,11.0,99505.600000,4.700000,5.166667,1.500000,1.666667,1.500000,...,1.700000,1.000000,1.533333,47.366667,2.833333,2.0,1.900000,308.182995,22884.433333,0.233333
1.692308,2023.0,7.641026,17393.051282,11.0,116997.717949,4.820513,4.948718,1.564103,1.692308,1.564103,...,1.820513,1.000000,1.461538,45.871795,3.205128,2.0,1.487179,316.661363,23125.435897,0.282051
1.696970,2023.0,5.969697,18057.666667,11.0,162387.939394,5.303030,3.727273,1.606061,1.696970,1.606061,...,1.818182,1.000000,1.636364,44.848485,3.090909,2.0,1.636364,343.591909,22780.575758,0.454545
1.714286,2023.0,5.880952,16491.000000,11.0,125916.357143,3.785714,2.952381,1.595238,1.714286,1.595238,...,1.904762,1.000000,1.547619,37.166667,3.642857,2.0,1.928571,224.135409,14406.785714,0.190476
1.720000,2023.0,6.280000,16912.440000,11.0,115131.720000,5.920000,4.120000,1.640000,1.720000,1.640000,...,1.680000,1.000000,1.520000,44.000000,3.640000,2.0,1.600000,444.425056,30221.560000,0.400000
1.733333,2023.0,6.600000,18144.266667,11.0,144519.933333,3.666667,5.000000,1.666667,1.733333,1.666667,...,2.066667,1.000000,1.333333,46.266667,3.333333,2.0,2.000000,211.859666,11489.466667,0.000000
1.745455,2023.0,6.272727,16292.218182,11.0,110283.963636,3.981818,3.509091,1.600000,1.745455,1.600000,...,1.981818,1.000000,1.636364,42.272727,3.290909,2.0,1.927273,318.719428,26578.763636,0.127273
1.750000,2023.0,4.611111,16945.236111,11.0,122435.312500,4.409722,4.756944,1.770833,1.750000,1.770833,...,2.270833,1.000000,1.611111,47.354167,3.333333,2.0,2.125000,247.265590,17057.604167,0.138889
1.758621,2023.0,7.034483,16166.931034,11.0,130039.931034,4.724138,4.862069,1.551724,1.758621,1.551724,...,1.724138,1.000000,1.551724,52.965517,3.034483,2.0,1.413793,443.578708,28883.586207,0.482759
1.769231,2023.0,7.564103,15996.730769,11.0,107507.897436,4.294872,5.512821,1.756410,1.769231,1.756410,...,1.974359,1.000000,1.525641,43.551282,2.717949,2.0,1.692308,255.977400,21817.858974,0.102564
1.777778,2023.0,2.888889,16081.555556,11.0,87124.888889,6.111111,3.333333,1.111111,1.777778,1.111111,...,1.666667,1.000000,1.444444,40.555556,3.222222,2.0,1.888889,484.887184,20971.111111,1.555556
1.800000,2023.0,7.711111,14612.000000,11.0,156718.288889,3.955556,3.600000,1.555556,1.800000,1.555556,...,1.977778,1.000000,1.488889,44.533333,3.222222,2.0,2.533333,294.444877,12949.422222,0.000000
1.818182,2023.0,8.125000,17106.420455,11.0,104290.625000,5.011364,4.079545,1.579545,1.818182,1.579545,...,2.079545,1.000000,1.545455,40.897727,3.170455,2.0,1.704545,293.986462,28920.215909,0.795455
1.823529,2023.0,6.000000,18422.588235,11.0,166932.352941,5.000000,5.000000,1.470588,1.823529,1.470588,...,1.764706,1.000000,1.352941,38.235294,2.823529,2.0,1.529412,292.693582,22148.588235,0.352941
1.857143,2023.0,4.428571,15573.047619,11.0,105133.047619,4.238095,4.761905,1.666667,1.857143,1.666667,...,1.809524,1.000000,1.428571,39.857143,3.047619,2.0,1.761905,490.045108,31223.761905,0.571429
1.868421,2023.0,6.184211,18135.394737,11.0,142383.000000,4.868421,3.631579,1.526316,1.868421,1.526316,...,1.973684,1.000000,1.421053,40.368421,3.263158,2.0,1.973684,287.716322,23100.868421,0.315789
1.875000,2023.0,8.250000,19301.375000,11.0,175277.125000,5.000000,5.500000,1.875000,1.875000,1.875000,...,1.875000,1.000000,1.500000,41.875000,2.750000,2.0,1.750000,152.767524,23489.375000,0.000000
1.925926,2023.0,5.592593,18163.074074,11.0,145814.703704,3.259259,3.222222,2.000000,1.925926,2.000000,...,1.777778,1.000000,1.518519,40.185185,2.666667,2.0,1.962963,334.669268,24768.074074,0.111111
1.937500,2023.0,7.125000,15417.687500,11.0,116693.937500,4.875000,6.437500,1.812500,1.937500,1.812500,...,2.062500,1.000000,1.437500,46.437500,2.812500,2.0,2.062500,277.027807,24602.875000,0.125000
1.960000,2023.0,7.240000,16857.600000,11.0,109114.520000,5.120000,4.600000,1.520000,1.960000,1.520000,...,2.080000,1.000000,1.480000,40.960000,3.480000,2.0,1.960000,401.232340,33790.400000,0.800000
1.961538,2023.0,5.115385,17270.807692,11.0,114683.769231,5.153846,3.153846,1.692308,1.961538,1.692308,...,2.730769,1.000000,1.346154,41.384615,3.730769,2.0,2.153846,184.070573,34762.076923,0.153846
2.000000,2023.0,6.496825,18174.522222,11.0,148188.732540,4.439683,5.626190,1.690476,2.000000,1.690476,...,2.059524,1.000000,1.457937,35.893651,3.051587,2.0,1.834921,178.655796,27548.741270,0.326190
2.037037,2023.0,7.185185,18552.296296,11.0,148164.000000,3.592593,3.296296,1.740741,2.037037,1.740741,...,2.370370,1.037037,1.555556,39.592593,3.148148,2.0,1.777778,207.009353,19544.111111,0.592593
2.062500,2023.0,6.875000,14539.312500,11.0,136621.437500,3.562500,5.500000,1.687500,2.062500,1.687500,...,2.812500,1.000000,1.500000,41.625000,2.937500,2.0,1.375000,221.776286,19986.812500,0.000000
2.166667,2023.0,8.875000,18196.916667,11.0,154042.916667,5.375000,4.958333,1.833333,2.166667,1.833333,...,2.250000,1.000000,1.541667,43.250000,3.750000,2.0,1.833333,298.825824,20203.416667,0.000000
2.250000,2023.0,5.150000,15998.350000,11.0,130252.250000,4.550000,3.550000,2.000000,2.250000,2.000000,...,2.450000,1.000000,1.500000,40.100000,3.300000,2.0,1.750000,251.420173,35824.100000,0.550000
2.272727,2023.0,6.909091,17185.636364,11.0,108463.954545,5.454545,4.045455,1.681818,2.272727,1.681818,...,2.545455,1.000000,1.500000,50.136364,3.318182,2.0,2.272727,427.643979,17417.318182,0.545455
2.500000,2023.0,3.000000,7258.000000,11.0,130901.000000,4.000000,8.000000,2.750000,2.500000,2.750000,...,2.250000,1.000000,1.500000,28.500000,4.000000,2.0,1.000000,267.894707,11588.000000,0.000000
2.666667,2023.0,6.000000,18714.000000,11.0,160113.000000,7.000000,7.000000,2.666667,2.666667,2.666667,...,2.000000,1.000000,1.333333,45.666667,2.666667,2.0,2.000000,146.051781,8005.000000,0.000000